name: "Regression Test - Tracking and Privacy (Beta) Test"
on: 
  schedule:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule
    # * is a special character in YAML so you have to quote this string
    - cron: '30 8,20 * * *'
  push:
    paths-ignore:
      - '**.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
      if: ${{ success() }}
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Setup dependencies using pip
      run: pip install -r requirements.txt
      if: ${{ success() }}
    - name: Download IP2LOCATION DB (Using repository secret)
      shell: bash
      env:
        IP2LOCATION_DOWNLOAD_URL: ${{ secrets.IP2LOCATION_DOWNLOAD_URL }}
      run: wget -q -O - $IP2LOCATION_DOWNLOAD_URL | tar -xvzf - -C data
      if: ${{ success() }}
    - name: Download Ads database (BlockListProject)
      run: |
        wget -q -O data/blocklistproject-ads-nl.txt https://blocklistproject.github.io/Lists/alt-version/ads-nl.txt
        echo "# data"
        ls data
      if: ${{ success() }}
    - name: Download Tracking database (BlockListProject)
      run: |
        wget -q -O data/blocklistproject-tracking-nl.txt https://blocklistproject.github.io/Lists/alt-version/tracking-nl.txt
        echo "# data"
        ls data
      if: ${{ success() }}
    - name: Download Services database (disconnect)
      run: |
        wget -q -O data/disconnect-services.json https://raw.githubusercontent.com/disconnectme/disconnect-tracking-protection/master/services.json
        echo "# data"
        ls data
      if: ${{ success() }}
    - name: Test Tracking and Privacy - USE DOCKER
      run: |
        python .github/workflows/verify_result.py -c true
        python default.py -t 23 -r -u https://mau.se/ -o .github/workflows/testresult-23.json
        python .github/workflows/verify_result.py -t 23
      if: ${{ success() }}
    - name: Setup Node.js (v1 version 14.x)
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
      if: ${{ success() }}
    - name: Setup Google Chrome browser (ONLY used for Sitespeed)
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        sudo apt-get update
        sudo apt-get --only-upgrade install google-chrome-stable
        google-chrome --version
      if: ${{ success() }}
    - name: Setup GeckoDriver (Used for Selenium)
      run: wget -q -O - https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz | tar -xvzf -
      if: ${{ success() }}
    - name: Setup Sitespeed.io npm package (ONLY used for Sitespeed)
      run: npm install -g sitespeed.io
      if: ${{ success() }}
    - name: Test Tracking and Privacy - USE NPM PACKAGE
      run: |
        python .github/workflows/verify_result.py -c false
        python default.py -t 23 -r -u https://mau.se/ -o .github/workflows/testresult-23.json
        python .github/workflows/verify_result.py -t 23
      if: ${{ success() }}
    - name: Test Directory - current
      run: |
        echo "# current folder"
        ls
      if: ${{ always() }}
    - name: Test Directory - data
      run: |
        echo "# data"
        ls data
      if: ${{ always() }}